### ISSUE TITLE
Should routing params be merged into the model?

### ISSUE THREAD

**Issue by eliperelman** [salsita/redux-boilerplate#10]
When using parameterized routes with react-router, these come into `props` as `params`. Should these somehow be automatically merged with the model supplied to the view?

```jsx
<Route path="users/:userId" />
```

```js
export default view(({ model, dispatch, params }) => {
  // there is model.userId, but also params.userId
});
```

Thoughts?

**Comment by tomkis1** [comment]
It depends, you can still mount them into model via `componentWillMount` / `componentWillReceiveProps` and dispatching them.

**Comment by eliperelman** [comment]
Makes sense.
