### ISSUE TITLE
Make routing connection generic 

### ISSUE THREAD

**Issue by eliperelman** [salsita/redux-boilerplate#12]
Since this repo uses Webpack, would it make sense to promote the generic connection of views to routes? Currently every time a new view is created that needs to be routed, the router configuration must be manually changed to add the new route and connect the view. This will be tedious and verbose for applications with many routes.

I do something similar to this in a work-in-progress project, do you think it makes sense to introduce something generic into this project?

https://github.com/eliperelman/taskcluster-tools/blob/fractal/src/common/pages.js

https://github.com/eliperelman/taskcluster-tools/blob/fractal/src/common/routing.js

**Comment by tomkis1** [comment]
Closing, obsolete with #13
