### ISSUE TITLE
Moving away from redux-elm?

### ISSUE THREAD

**Issue by jmatsushita** [salsita/redux-boilerplate#14]
Hi there,

I just saw that you have updated this boilerplate significantly. But it seems that `redux-elm` is not used anymore here. Is that saying something about the future of your involvement in `redux-elm`?

Cheers!

Jun

**Comment by tomkis1** [comment]
Hello @jmatsushita

Yes it indeed looks like we are moving away from `redux-elm`. I am planning to write an article to advocate our decision. Stay tuned.

However, it doesn't mean that `redux-elm` must be a wrong choice.

**Comment by jmatsushita** [comment]
Thanks for the heads up! Will be interested in hearing what you have in
your sights.

**Comment by jmatsushita** [comment]
If you get around to it, a migration guide to this new boilerplate would be a great christmas present :)
