### ISSUE TITLE
Config file is included in the build itself

### ISSUE THREAD

**Issue by tomasji** [salsita/redux-boilerplate#5]
As an administrator I'd like to be able to download a production build artefact, install it and configure it for the given host. Later I might even need to change the configuration, without re-installing the product.

The current boilerplate webpack (e.g. in Circles project) however bundles the config file into the build (dist/server.js). Some top-level configuration items can be changed via an environment variable, but it is not sufficient.

I'd like to have a normal (json) config file, that is loaded at startup (or reloaded upon the HUP signal) and is not hard-coded in the build.

**Comment by tomkis1** [comment]
Obsolete with #13, closing
